-- (9 Okt 2026) Kegiatan induk + tahap proses bisnis SIGAP. Sudah diterapkan ke DB (migration "sigap_induk_tahap_20261009"); salinan ini untuk arsip repo.
create table if not exists public.sigap_induk (
  kode text primary key,
  nama text not null,
  pendek text not null,
  ikon text not null default 'bencana',
  kegiatan_ids bigint[] not null default '{}',
  urutan integer not null default 0,
  aktif boolean not null default true,
  dibuat_at timestamptz not null default now()
);

create table if not exists public.sigap_tahap (
  id bigint generated by default as identity primary key,
  induk_kode text not null references public.sigap_induk(kode) on update cascade on delete cascade,
  kode text not null,
  urutan integer not null,
  nama text not null,
  uraian text,
  isi text[] not null default '{}',
  buka_mode text not null default 'langsung' check (buka_mode in ('langsung','setelah_sebelumnya','tanggal')),
  buka_tanggal date,
  aktif boolean not null default true,
  diubah_at timestamptz not null default now(),
  diubah_oleh text,
  unique (induk_kode, kode)
);

alter table public.sigap_induk enable row level security;
alter table public.sigap_tahap enable row level security;

insert into public.sigap_induk (kode, nama, pendek, ikon, kegiatan_ids, urutan)
values ('pascabencana', 'Pendataan Pascabencana', 'Pendataan Pascabencana', 'bencana', '{1,3}', 1)
on conflict (kode) do nothing;

insert into public.sigap_tahap (induk_kode, kode, urutan, nama, uraian, isi) values
  ('pascabencana', 'perencanaan', 1, 'Perencanaan', 'Kesediaan dikonfirmasi dan wilayah tugas diterima.', '{konfirmasi}'),
  ('pascabencana', 'pelatihan',   2, 'Pelatihan',   'Langkah pelatihan dan Transport Lokal pelatihan.', '{pelatihan,"translok:3"}'),
  ('pascabencana', 'pendataan',   3, 'Pendataan',   'Wilayah tugas tim serta Transport Lokal dan administrasi.', '{wilayah_tim,"translok:1"}'),
  ('pascabencana', 'evaluasi',    4, 'Evaluasi',    'Evaluasi kegiatan dan umpan balik petugas.', '{}')
on conflict (induk_kode, kode) do nothing;
